Wardo/Wardo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("products.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('comments/', include('comments.urls', namespace="comments")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

# + static nos permite servir archivos estaticos como imagenes

Wardo/accounts/urls.py
#el login y logout atraves de django auth
from django.contrib.auth.views import login, logout
from django.urls import path
from accounts.views import signup

app_name = "accounts"

urlpatterns = [
	path('login',login, {'template_name': 'accounts/login.html'}, name='login'),
	# logout no tiene template, solo nos saca de la sesion y redirecciona
	path('logout',logout, {'next_page':'/'}, name="logout"),
	path('signup',signup, name="signup"),
]
#creo usuarios por defecto con:
# ./manage.py createsuperuser
# 

Wardo/comments/urls.py
from comments.views import create_comment
from django.urls import path

app_name = "comments"

urlpatterns = [
	path('createcomment', create_comment, name="createcomment")
]

Wardo/products/urls.py
from django.urls import path
from products.views import (
	HomeView, 
	ProductDetailView,
	ProductBuyView,
	search_result,
	CategoryView,
)


urlpatterns = [
	path("", HomeView.as_view(),name="home"),
	path('products/search/', search_result, name="searchresult"),
	path("products/<slug:slug>/", ProductDetailView.as_view(),name="detail"),
	path("products/<slug:slug>/buy/", ProductBuyView.as_view(),name="buy"),
	path('categories/<category>/', CategoryView.as_view(), name="categories"),

]

Wardo/products/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

# Create your models here.
class Product(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	title = models.CharField(max_length=255)
	description = models.TextField(max_length=255)
	price = models.IntegerField()
	slug = models.SlugField()
	categories = models.ManyToManyField('products.ProduCategory')

	#funcion para obtener una url absoluta del producto
	def get_absolute_url(self):
		#return reverse("nombre de nuestra vista", params)
		#queda asi products/<slug:slug>
		return reverse("detail", kwargs={'slug': self.slug})

	def __str__(self):
		return self.title

class ProductImage(models.Model):
	#si un producto se borra sus iamgenes tambien
	#related name para definir la relacion inversa
	#para referir el product con las imagenes
	product = models.ForeignKey(
		'products.Product',
		on_delete=models.CASCADE,
		related_name='images'
	)
	#ImageField referencia una ubicacion
	#Instalo Pillow sobre el proyecto para el manejo de imagenes
	image = models.ImageField()

	def __str__(self):
		return self.image.url	

class ProduCategory(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	name = models.CharField(max_length=255)
	slug = models.SlugField()

	def __str__(self):
		return self.name

#Guardar los pagos
class LogBuy(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	product = models.ForeignKey(
		'products.Product',
		on_delete = models.CASCADE,
	)
	user = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		on_delete = models.CASCADE,
		#la relacion es opcional
		null=True,
		blank=True,
	)
	def __str__(self):
		return "product {} buyed".format(self.product)

Wardo/products/forms.py
from django import forms
from products.models import Product
#form en vista de detalle y en vista de crear un comentario
class SearchForm(forms.ModelForm):

	class Meta:
		model = Product
		fields = [
			'title',
		]

Wardo/products/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, DetailView
from products.models import Product, LogBuy, ProduCategory
from comments.forms import CommentForm
from products.forms import SearchForm
from django.http import HttpResponseNotFound
import stripe
from django.conf import settings
# Create your views here.
#vista del search
def search_result(request):
	form = SearchForm(request.POST)

	if form.is_valid():
		#trae el formulario sin guardarlo
		resultSearch = form.save(commit=False)
		queryResult = resultSearch.title
		products = Product.objects.filter(title__icontains=queryResult)
		return render(request, "products/search.html", {'products':products, 'queryResult':queryResult})
	else:	
		return HttpResponseNotFound("<h1>Your search is incorrect</h1>")
			

#vista de home en products
class HomeView(TemplateView):
	template_name='products/home.html'

	#le pasamos en el contexto todos los productos
	def get_context_data(self, *args, **kwargs):
		search_form = SearchForm()
		products = Product.objects.all()
		category = ProduCategory.objects.all()
		return {'products': products, 'search_form':search_form, 'categories':category}

#vista para detalle del prodcuto
#solo si pongo el nombre del template con un guin bajo y detail
# el toma el archivo por defecto
class ProductDetailView(DetailView):
	model = Product

	def get_context_data(self, *args, **kwargs):
		#para que no se sobrescriba si no escribir al final del context
		context = super().get_context_data(*args, **kwargs)
		comment_form = CommentForm()
		context['comment_form'] = comment_form
		return context


class CategoryView(TemplateView):

	template_name = 'products/home.html'

	def get_context_data(self, *args, **kwargs):
		
		try:
			categoryall = ProduCategory.objects.all()
			category = ProduCategory.objects.get(name=kwargs['category'])
			productfilter = Product.objects.filter(categories=category)
		except category.DoesNotExist as e:
			raise Http404('The Category {} does no exist'.format(kwargs['category']))
		else:
			pass
		finally:
			pass
		return {'products' : productfilter, 'categories': categoryall}

class ProductBuyView(DetailView):
	model = Product
	template_name = 'products/buy.html'

	#Recolectando el token que da Stripe en el post
	def post(self, request,*args, **kwargs):
		stripe.api_key = settings.STRIPE_API_KEY
		#En el post vienen el token en este param
		token = request.POST['stripeToken']
		#Ya que estamos utilizando un detailView podemos traer el producto asi
		product = self.get_object()
		error_message = None
		try:
			#charge Genera un carga unico
			charge = stripe.Charge.create(
		            amount=product.price,
		            currency='usd',
		            description="cobro por {}".format(product.title),
		            statement_descriptor="cobro Wardo",
		            source=token
				)
		except stripe.error.CardError as e:
			body = e.json_body
			err = body['error']
			error_message = err['message']
		except stripe.error.StripeError as e:
			error_message = "Can't process your payment, please try again later"

		if error_message:
			return render(request, "products/failed.html", {'error_message': error_message, 'product': product})
		
		buyer = None
		if request.user.is_authenticated:	
			buyer = request.user

		#guardo el registro si fue exitoso
		LogBuy.objects.create(
			product = product,
			user = buyer,
		)
		
		#Opcional enviar el debug de stripe
		return render(request, "products/success.html", {'debug_info': charge, 'product': product})

Wardo/products/templates/products/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{title|default:"Wardo"}}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://bootswatch.com/4/minty/bootstrap.min.css" rel="stylesheet">
    <!-- <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet"> -->

    <!-- Custom styles for this template -->

    {% block css %}{% endblock css %}
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: rgba(120, 194, 173,0.8);">
      <div class="container">
        <a class="navbar-brand text-white" href="/">Wardo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"></a>
            </li>
            <form class="form-inline my-2 my-lg-0" method="post" action="{% url "searchresult" %}">
              {% csrf_token %}
              <input name="{{search_form.title.name}}" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
            </form>
            {% if request.user.is_authenticated%}
            <li class="nav-item">
              <a class="nav-link text-muted" href="#">{{request.user.username}}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url "accounts:logout" %}">logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "accounts:login" %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock content %}
    <!-- Footer -->
    <footer class="py-2 bg-primary">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Will {% now "Y" %}</p>
      </div>
      <!-- /.container -->
    </footer>
  {% block js%}{% endblock %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  </body>

</html>

Wardo/products/templates/products/buy.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% block css %}
<link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">

<style type="text/css">
#product-image {
  max-width: 350px;
}
</style>

{% endblock %}
{% block content %}
<script src="https://js.stripe.com/v3/"></script>
<div class="container">

  <div class="row p-3">
		<div class="col-xs-2 m-3 card"><img id="product-image" class="img-responsive" src="{{product.images.first.image.url}}">
		</div>
		<div class="col-xs-4 m-3">
			<h4 class="product-name"><strong>{{object.title}}</strong></h4><h4><small>{{object.description}}</small></h4>
		</div>
	</div>
<div class="row p-2 ">
  <div class="col-xs-12 col-md-6">
  <form action="." method="post" id="payment-form">
    {% csrf_token %}

    <h2>Payment Data</h2>
    <br>
    <div id="card-element">
      <!-- a Stripe Element will be inserted here. -->
    </div>
    <div id="card-errors" role="alert"></div>
    <br>
    <button type="submit" class="btn btn-success">Buy</button>
  </form>

  </div>
  </div>
</div>


<script type="text/javascript">
var stripe = Stripe("pk_test_SnqbRnvqT3lLPv7h5EFuihVN");
var elements = stripe.elements();



var style = {
  base: {
    color: '#32325d',
    lineHeight: '18px',
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '20px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};
// Create an instance of the card Element
var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>
card.mount('#card-element');

card.addEventListener('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});


function stripeTokenHandler(token) {
  console.log(token);
  // // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('payment-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}
// Create a token or display an error when the form is submitted.
var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the customer that there was an error
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server
      // console.log(result.token);
      stripeTokenHandler(result.token);
    }
  });
});
</script>
{% endblock content %}

Wardo/products/templates/products/failed.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% block css %}
  <link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">
{% endblock%}

{% block content %}
<div class="container">

<div class="row">
  <div class="col-xs-12 col-md-12 m-3">
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">Payment failed</h4>
      <p>Sorry, something happened with the payment to {{product.title}}</p>
      <p>{{error_message}}</p>
      <hr>
    </div>
    <a href="/"><button type="button" class="btn btn-primary", name="button">Volver</button></a>
  </div>

</div>
</div>
{% endblock %}

Wardo/products/templates/products/home.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% block css %}
  <link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">
  <style media="screen">
    a {
      color: darkslategray;
    }
  </style>
{% endblock css%}

{% block content %}
    <!-- Page Content -->
    <div class="container">

      <!-- Page Heading -->
      <br>
      <h1 class="lead">Your Store in 1 Click.</h1>
      <h1 class="my-4">Products
        <!-- <small>buy one</small> -->
      </h1>
      
      <ul class="nav nav-tabs">
        {% for category in categories %}
        {% url "categories" category=category.name as the_url %}
        <li class="nav-item">
          {% ifequal request.path the_url %}
          <a class="nav-link active" href="{{the_url}}">{{category.name|capfirst}}</a>
          {% else %}
          <a class="nav-link" href="{{the_url}}">{{category.name|capfirst}}</a>
          {% endifequal %}
        </li>
        {% endfor %}
      </ul>
      <br>
      {% for product in products %}
      {% if forloop.counter0 != 0 and forloop.counter0|divisibleby:"3" %}
      </div>
      {% endif %}
      {% if forloop.counter0|divisibleby:"3" %}
      <div class="row">
      {% endif %}
      <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
          <a href="{{product.get_absolute_url}}" style="align-self: center"><img class="" src="{{product.images.first.image.url}}" style="max-height: 200px; max-width:100% !important; display:block; " alt=""></a>
          <div class="card-body">
            <h4 class="card-title">
              <a href="{{product.get_absolute_url}}">{{product.title}}</a>
            </h4>
            <p class="card-text">{{product.description}}</p>
          </div>
        </div>
      </div>
      {% endfor %}
      </div>
<!--
      <div class="row">
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project One</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur eum quasi sapiente nesciunt? Voluptatibus sit, repellat sequi itaque deserunt, dolores in, nesciunt, illum tempora ex quae? Nihil, dolorem!</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Two</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Three</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos quisquam, error quod sed cumque, odio distinctio velit nostrum temporibus necessitatibus et facere atque iure perspiciatis mollitia recusandae vero vel quam!</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Four</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Five</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">Project Six</a>
              </h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque earum nostrum suscipit ducimus nihil provident, perferendis rem illo, voluptate atque, sit eius in voluptates, nemo repellat fugiat excepturi! Nemo, esse.</p>
            </div>
          </div>
        </div>
      </div> -->
      <!-- /.row -->

      <!-- Pagination -->
      <!-- <ul class="pagination justify-content-center">
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">1</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul> -->

    </div>
    <!-- /.container -->
{% endblock content%}

Wardo/products/templates/products/product_detail.html
{% extends 'products/base.html' %}
{% load staticfiles %}
{% block css %}
  <link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">
{% endblock css%}
{% block content %}

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">
          <!-- Title -->
          <h1 class="mt-4">{{product.title}}</h1>

          <!-- Author -->
          <!-- <p class="lead">
            by
            <a href="#">Start Bootstrap</a>
          </p> -->

          <hr>

          <!-- Date/Time -->
          <p>Posted on {{product.created_at}}</p>

          <hr>

          <div class="row">
            <div class="col-lg-9">
              <div class="tab-content" id="nav-tabContent">
                {% for imagen in product.images.all %}
                  {% if forloop.counter ==  1 %}
                    <div class="tab-pane fade show active" id="list-img-{{ forloop.counter }}" role="tabpanel" aria-labelledby="img-list-{{ forloop.counter }}">
                      <img class="img-fluid rounded" src="{{imagen.image.url}}" alt="" style="max-height: 400px;">
                    </div> 
                  {% else %}
                    <div class="tab-pane fade show" id="list-img-{{ forloop.counter }}" role="tabpanel" aria-labelledby="img-list-{{ forloop.counter }}">
                      <img class="img-fluid rounded" src="{{imagen.image.url}}" alt="" style="max-height: 400px;">
                    </div>   
                  {% endif %}
                {% endfor %}
              </div>
            </div>
            <div class="col-lg-3">
              <div class="list-group" id="list-tab" role="tablist">
                {% for imagen in product.images.all %}
                  {% if forloop.counter ==  1 %}
                    <a class="list-group-item list-group-item-action active" id="img-list-{{ forloop.counter }}" data-toggle="list" href="#list-img-{{ forloop.counter }}" role="tab" aria-controls="img-{{ forloop.counter }}">
                      <img class="img-fluid rounded" src="{{imagen.image.url}}" alt="" style="max-height: 100px;max-width: 100px;">
                    </a>
                  {% else %}
                    <a class="list-group-item list-group-item-action" id="img-list-{{ forloop.counter }}" data-toggle="list" href="#list-img-{{ forloop.counter }}" role="tab" aria-controls="img-{{ forloop.counter }}">
                      <img class="img-fluid rounded" src="{{imagen.image.url}}" alt="" style="max-height: 100px;max-width: 100px;">
                    </a>
                  {% endif %}
                {% endfor %}
              </div>
            </div>
          </div>
          <hr>
            
          <!-- Post Content -->
          <div class="row">
            <div class="col-lg-3">
              <div class="list-group" id="list-tab" role="tablist">
                <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Description</a>
                <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Features</a>
              </div>
            </div>
            <div class="col-lg-9">
              <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">
                  <p class="lead">{{product.description|capfirst}}</p>
                </div>
                <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list"><p>Features of all items</p></div>
                {% for imagen in product.images.all %}
                  
                {% endfor %}
              </div>
            </div>
          </div>

          <hr>

          <!-- Comments Form -->
          {% if request.user.is_authenticated %}
          <h4 id="comments">Comments</h4>
          <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
              <form method="post" action="{% url "comments:createcomment" %}">
                {% csrf_token %}
                <div class="form-group">
                  <textarea name="{{comment_form.content.name}}" class="form-control" rows="3"></textarea>
                  <input type="hidden" name="{{comment_form.product.name}}" value="{{product.id}}">
                </div>
                <button type="submit" class="btn btn-outline-primary">Submit</button>
              </form>
            </div>
          </div>
          {% else %}
          <p>If you want comment, please signin.</p>
          {% endif %}

          <!-- Single Comment -->
          {% for comment in product.comments.all reversed %}
          <div id="0" class="media mb-4">
            
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/80x80" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{comment.author.username}}</h5>
              <span>{{comment.content}}</span>
              <p><small>{{comment.updated_at}}</small></p>
            </div>
            
          </div>
          {% endfor %}

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <form class="form-inline my-2 my-lg-0" method="post" action="{% url "searchresult" %}">
                {% csrf_token %}
              <div class="input-group mb-3">
                <input name="{{search_form.title.name}}" type="search" class="form-control" placeholder="Search for..." aria-label="Recipient's username" aria-describedby="basic-addon2">
                <div class="input-group-append">
                  <button class="btn btn-outline-secondary" type="submit">Go!</button>
                </div>
              </div>
              </form>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    {% for category in product.categories.all %}
                    <li>
                      <a href="{% url "categories" category=category.name %}">{{category.name|capfirst}}</a>
                    </li>
                    {% endfor %}
                  </ul>
                </div>

            </div>
          </div>

          <div class="card my-4">
            <h5 class="card-header">Pricing</h5>
            <div class="card-body">
              Only ${{product.price}}
              <a href="{% url "buy" slug=product.slug %}"><button type="button" class="btn btn-success">Buy</button></a>
            </div>
          </div>

        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

{% endblock content %}

Wardo/products/templates/products/success.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% block css %}
  <link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">
{% endblock%}

{% block content %}
<div class="container">

<div class="row">
  <div class="col-xs-12 col-md-12 m-3">
    <div class="alert alert-info" role="alert">
      <h4 class="alert-heading">Payment success</h4>
      <p>Congratuliations, you just buy {{product.title}}</p>
      <hr>
      <p>DEBUG INFO {{debug_info}}</p>
    </div>
    <a href="/"><button type="button" class="btn btn-primary", name="button">Volver</button></a>
  </div>

</div>
</div>
{% endblock %}

Wardo/products/templates/products/test.html
{% extends "products/base.html" %}
{% load staticfiles %}
{% block css%}
<link href="{% static "css/3-col-portfolio.css" %}" rel="stylesheet">
<style media="screen">
  a {
    color: white;
  }
</style>
{% endblock %}
{% block content %}
<div class="container">
	
	<h1>Hello {{user.username}}</h1>
	<a class="btn btn-outline-success" href="{% url "accounts:login" %}?next={{request.path}}">Log in</a>
	<a class="btn btn-outline-danger" href="{% url "accounts:logout" %}">Log out</a>
	{# next apunta a la siguiente url luego de estar en esa pagina #}

</div>
{% endblock %}